import { randomBytes } from 'node:crypto';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { openPdDatabase, closePdDatabase } from '@/lib/pd-admin/db/database';
import { persistSession, hashAdministrativeFingerprint } from '@/lib/pd-admin/auth/session-store';
const root=mkdtempSync('/private/tmp/steel-production-qa-');
const environment={NODE_ENV:'development' as const,STEEL_PRODUCT_PAID_SERVICES_ALLOWED:'false',STEEL_PRODUCT_LOCAL_AI_ENABLED:'false',YANDEX_AI_ENABLED:'false',STEEL_PRODUCT_QUOTE_AI_REVIEW_REQUIRED:'false',PD_ADMIN_ENABLED:'true',PD_ADMIN_DB_PATH:root+'/test.sqlite',PD_EXPORT_PATH:root+'/exports',PD_SEARCH_HMAC_KEY:randomBytes(32).toString('hex'),PD_SESSION_HASH_KEY:randomBytes(32).toString('hex'),PD_AUDIT_CHAIN_KEY:randomBytes(32).toString('hex'),STEEL_PRODUCT_PRIVATE_PRODUCTION_REPORT_ROOT:root+'/reports',IP_HASH_SALT:'synthetic-browser-test-salt-only',STEEL_PRODUCT_PRIVATE_CALCULATION_BASIS_PATH:root+'/basis.json',STEEL_PRODUCT_METAL_MULTIPLIER:'1.1',STEEL_PRODUCT_DRAW_PCT:'0',STEEL_PRODUCT_FINAL_PCT:'0',STEEL_PRODUCT_FIXED_ADD_RUB:'0',STEEL_PRODUCT_FIXED_ADD_ENABLED:'false',STEEL_PRODUCT_ROUND_STEP_RUB:'0.01'};
const db=openPdDatabase({databasePath:environment.PD_ADMIN_DB_PATH,environment});
const now=new Date().toISOString();
db.prepare("INSERT INTO users(id,username,display_name,password_hash,password_algorithm,password_version,role,must_change_password,created_at,updated_at) VALUES ('qa','synthetic-qa','Тестовый технолог','invalid-password','scrypt',1,'ADMIN',0,?,?)").run(now,now);
const userAgent='SteelProductionBrowserQA';
const session=persistSession(db,{userId:'qa',hashKey:environment.PD_SESSION_HASH_KEY,ipHash:hashAdministrativeFingerprint('unknown',environment.PD_SESSION_HASH_KEY,'ip'),userAgentHash:hashAdministrativeFingerprint(userAgent,environment.PD_SESSION_HASH_KEY,'user-agent'),idleMinutes:60,absoluteHours:2});
closePdDatabase(db,environment.PD_ADMIN_DB_PATH);
const source={id:'synthetic-qa',label:'SYNTHETIC TEST ONLY',confirmedAt:now,note:'Not a production tariff'};
writeFileSync(environment.STEEL_PRODUCT_PRIVATE_CALCULATION_BASIS_PATH,JSON.stringify({version:'SYNTHETIC-BROWSER-QA',rateBook:{laserRubPerM:['cold','hot'].map(materialId=>({materialId,thicknessMm:1,rateRub:10,pierceRubEach:1,source}))},materialPriceSnapshots:[{sourceId:'atlantik-smolensk',fetchedAt:now,sourceDate:now,status:'ok',rows:['cold','hot'].map(materialId=>({materialId,thicknessMm:1,rubPerTon:100000,source:'SYNTHETIC TEST ONLY',sourceDate:now,size:'1250x2500',exactThickness:true}))}]}),{mode:0o600});
writeFileSync('/private/tmp/steel-production-qa.json',JSON.stringify({environment,session,userAgent}),{mode:0o600});
console.log('Synthetic isolated test database prepared.');
