import Link from "next/link";
import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { EmptyState, Pager, Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { listAuthorityRequests } from "@/lib/pd-admin/authority-requests/repository";

export const dynamic = "force-dynamic";
export default async function AuthorityRequestsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const context = await requirePdPageContext("VIEW_AUTHORITY_REQUESTS"); const result = listAuthorityRequests(context, Number((await searchParams).page || 1)); const canCreate = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close();
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Официальные запросы" title="Запросы государственных органов" description="Запрос регистрируется и проверяется человеком. Название органа само по себе не подтверждает полномочия." />{canCreate ? <Link prefetch={false} href="/internal/personal-data/authority-requests/new" className="mb-4 inline-block bg-steel-orange-deep px-5 py-3 text-xs font-bold uppercase">Зарегистрировать запрос</Link> : null}<Panel>{result.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="text-white/40"><tr>{["Номер", "Орган", "Документ", "Получено", "Проверка", "Статус", "Срок", "Заявок"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{result.items.map((item) => <tr key={item.id} className="border-b border-white/5"><td className="px-3 py-3"><Link prefetch={false} href={`/internal/personal-data/authority-requests/${item.id}`} className="text-[#ea5b0c]">{item.registrationNumber}</Link></td><td className="px-3 py-3">{item.authorityName}</td><td className="px-3 py-3">{item.requestNumber}</td><td className="px-3 py-3">{new Date(item.receivedAt).toLocaleString("ru-RU")}</td><td className="px-3 py-3"><StatusPill status={item.verificationStatus === "VERIFIED" ? "ready" : "warning"} label={item.verificationStatus} /></td><td className="px-3 py-3">{item.status}</td><td className="px-3 py-3">{new Date(item.extendedDueAt || item.dueAt).toLocaleString("ru-RU")}</td><td className="px-3 py-3">{item.leadsCount}</td></tr>)}</tbody></table></div> : <EmptyState>Запросов пока нет.</EmptyState>}<Pager basePath="/internal/personal-data/authority-requests" {...result} /></Panel></InternalShell>;
}
