import assert from 'node:assert/strict';
import test from 'node:test';
import {estimateThinLaserRate} from '../lib/instant-quote/laser-rate-estimate';
import {calculateFactualProductionCost,type FactualRateBook} from '../lib/instant-quote/factual-calculation';
const source={id:'synthetic',label:'Test',confirmedAt:'2026-09-22',note:'Synthetic test values'};
const book=():FactualRateBook=>({laserRubPerM:[{materialId:'zinc',thicknessMm:.8,rateRub:50,from100mRubPerM:40,from500mRubPerM:30,pierceRubEach:2,source},{materialId:'zinc',thicknessMm:1,rateRub:60,from100mRubPerM:48,from500mRubPerM:36,pierceRubEach:2,source}],bendRubEach:null,weldRubPerM:null,powderRubPerM2:null});
test('owner requested .7 extrapolation preserves private basis and marks provenance',()=>{const b=book(),before=JSON.stringify(b),r=estimateThinLaserRate(b,'zinc',.7)!;assert.equal(r.rateRub,45);assert.equal(r.from100mRubPerM,36);assert.equal(r.from500mRubPerM,27);assert.equal(r.pierceRubEach,2);assert.match(r.source.label,/требует подтверждения/);assert.equal(JSON.stringify(b),before);});
test('never extrapolate other thickness/material, missing sources, negative rate or overriding exact rate',()=>{for(const t of [.5,.6,.9,1.2])assert.equal(estimateThinLaserRate(book(),'zinc',t),null);assert.equal(estimateThinLaserRate(book(),'cold',.7),null);let b=book();b.laserRubPerM.pop();assert.equal(estimateThinLaserRate(b,'zinc',.7),null);b=book();b.laserRubPerM[1].rateRub=200;assert.equal(estimateThinLaserRate(b,'zinc',.7),null);b=book();b.laserRubPerM.push({...b.laserRubPerM[0],thicknessMm:.7});assert.equal(estimateThinLaserRate(b,'zinc',.7),null);});
test('calculation keeps actual .7 metal price and marks derived laser rate',()=>{const r=calculateFactualProductionCost({materialId:'zinc',thicknessMm:.7,quantity:1,operations:['laser-cutting'],geometry:{widthMm:100,heightMm:100,areaMm2:10000,blankAreaMm2:10000,cutLengthMm:400,pierceCount:1},rateBook:book(),marketPrice:{materialId:'zinc',thicknessMm:.7,rubPerTon:100000,source:'synthetic',sourceDate:'2026-09-22',fetchedAt:'2026-09-22T00:00:00Z',exactThickness:true}});assert.equal(r.estimatedRateUsed,true);assert.equal(r.status,'complete');assert.equal(r.lines.find(x=>x.code==='laser-cutting')!.rateRub,45);assert.equal(r.thicknessMm,.7);assert.ok(r.warnings.length);});
