import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { EmptyState, Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { listSystems } from "@/lib/pd-admin/registers/repository";

export const dynamic = "force-dynamic";
export default async function SystemsPage() {
  const context = await requirePdPageContext("VIEW_SYSTEMS_REGISTRY"); const items = listSystems(context) as Array<Record<string, unknown>>; const canManage = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close();
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Карта обработки" title="Реестр систем и подрядчиков" description="Неподтверждённые сведения должны иметь статус проверки, а не отображаться как установленный факт." />{canManage ? <Panel title="Добавить запись" className="mb-4"><SecureMutationForm csrfToken={shell.csrfToken} endpoint="/api/internal/personal-data/systems" submitLabel="Зарегистрировать систему" fields={[{ name: "systemName", label: "Система", required: true }, { name: "purpose", label: "Цель", kind: "textarea", required: true }, { name: "provider", label: "Поставщик", required: true }, { name: "databaseCountry", label: "Страна баз", required: true }, { name: "dataCategories", label: "Категории данных", kind: "textarea", required: true }, { name: "legalBasis", label: "Основание", kind: "textarea", required: true }, { name: "agreementReference", label: "Договор / документ" }, { name: "retentionDescription", label: "Сроки хранения", kind: "textarea", required: true }, { name: "responsibleUser", label: "Ответственный", required: true }, { name: "administrators", label: "Администраторы", kind: "textarea", required: true }, { name: "mfaStatus", label: "MFA", required: true }, { name: "exportMethod", label: "Способ выгрузки", kind: "textarea", required: true }, { name: "deletionMethod", label: "Способ удаления", kind: "textarea", required: true }, { name: "lastReviewAt", label: "Последняя проверка", kind: "datetime-local" }, { name: "status", label: "Статус", required: true, defaultValue: "REVIEW_REQUIRED" }]} /></Panel> : null}<Panel>{items.length ? <div className="grid gap-3 xl:grid-cols-2">{items.map((item) => <article key={String(item.id || item.system_name)} className="border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{String(item.system_name)}</h2><StatusPill status={item.status === "CONFIRMED" ? "ready" : "warning"} label={String(item.status)} /></div><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div><dt className="text-white/40">Поставщик</dt><dd>{String(item.provider)}</dd></div><div><dt className="text-white/40">Страна</dt><dd>{String(item.database_country)}</dd></div><div><dt className="text-white/40">MFA</dt><dd>{String(item.mfa_status)}</dd></div><div><dt className="text-white/40">Проверено</dt><dd>{String(item.last_review_at || "не подтверждено")}</dd></div></dl></article>)}</div> : <EmptyState>Реестр не заполнен.</EmptyState>}</Panel></InternalShell>;
}
