import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { MetricCard, Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { retentionDashboard } from "@/lib/pd-admin/retention/service";

export const dynamic = "force-dynamic";
export default async function RetentionPage() {
  const context = await requirePdPageContext("VIEW_RETENTION"); const result = retentionDashboard(context); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close();
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Сроки хранения" title="Retention dashboard" description="Страница ничего не удаляет. Она рассчитывает сроки и показывает все действующие блокировки на момент проверки." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Истекает 30 дней" value={result.summary.expires30Days} /><MetricCard label="Истекает 7 дней" value={result.summary.expires7Days} tone="warning" /><MetricCard label="Истекло" value={result.summary.expired} tone="critical" /><MetricCard label="Заблокировано" value={result.summary.blocked} tone="warning" /><MetricCard label="Кандидаты" value={result.summary.candidates} /></div><Panel className="mt-4"><div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left text-xs"><thead className="text-white/40"><tr>{["Request ID", "Истекает", "Consent до", "Статус", "Блокировки"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{result.items.map((item) => <tr key={item.requestId} className="border-b border-white/5"><td className="px-3 py-3">{item.requestId}</td><td className="px-3 py-3">{new Date(item.expiresAt).toLocaleString("ru-RU")}</td><td className="px-3 py-3">{item.consentExpiresAt ? new Date(item.consentExpiresAt).toLocaleString("ru-RU") : "неизвестно"}</td><td className="px-3 py-3"><StatusPill status={item.eligible ? "warning" : "ready"} label={item.eligible ? "кандидат" : "сохранить"} /></td><td className="px-3 py-3">{item.blockers.length ? item.blockers.join(", ") : "Нет"}</td></tr>)}</tbody></table></div>{result.truncated ? <p className="mt-3 text-xs text-amber-200">Показаны первые 500 записей.</p> : null}</Panel></InternalShell>;
}
