import Link from "next/link";
import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { EmptyState, Pager, Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { listIncidents } from "@/lib/pd-admin/incidents/repository";

export const dynamic = "force-dynamic";
export default async function IncidentsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const context = await requirePdPageContext("VIEW_INCIDENTS"); const result = listIncidents(context, Number((await searchParams).page || 1)); const canCreate = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close();
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Реагирование" title="Журнал инцидентов" description="Необходимость уведомления Роскомнадзора оценивает ответственный сотрудник; система не принимает это решение автоматически." />{canCreate ? <Link prefetch={false} href="/internal/personal-data/incidents/new" className="mb-4 inline-block bg-steel-orange-deep px-5 py-3 text-xs font-bold uppercase">Зарегистрировать инцидент</Link> : null}<Panel>{result.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-white/40"><tr>{["ID", "Выявлен", "Статус", "Системы", "Категории", "Субъектов", "Уведомление"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{result.items.map((item) => <tr key={String(item.id)} className="border-b border-white/5"><td className="px-3 py-3"><Link prefetch={false} href={`/internal/personal-data/incidents/${item.id}`} className="text-[#ea5b0c]">{String(item.id).slice(0, 12)}…</Link></td><td className="px-3 py-3">{new Date(String(item.detected_at)).toLocaleString("ru-RU")}</td><td className="px-3 py-3"><StatusPill status={item.stage4_status === "CLOSED" ? "ready" : "warning"} label={String(item.stage4_status)} /></td><td className="px-3 py-3">{String(item.affected_systems)}</td><td className="px-3 py-3">{String(item.data_categories)}</td><td className="px-3 py-3">{String(item.estimated_subjects ?? "неизвестно")}</td><td className="px-3 py-3">{item.rkn_notification_required ? "Требуется" : "Не определено / нет"}</td></tr>)}</tbody></table></div> : <EmptyState>Инцидентов нет.</EmptyState>}<Pager basePath="/internal/personal-data/incidents" {...result} /></Panel></InternalShell>;
}
