import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { getSubjectRequest } from "@/lib/pd-admin/subject-requests/repository";

export const dynamic = "force-dynamic";
export default async function SubjectRequestPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const context = await requirePdPageContext("VIEW_SUBJECT_REQUESTS"); const item = getSubjectRequest(context, id); const canChange = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role);
  const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close(); const endpoint = `/api/internal/personal-data/subject-requests/${encodeURIComponent(id)}`;
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Обращение субъекта" title={item.registrationNumber} description="Расчётная и подтверждённая даты сохраняются отдельно; продления и проверки личности имеют собственную историю." />
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Карточка"><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Статус", item.status], ["Идентификация", item.identityStatus], ["Имя", item.subjectName], ["Контакт", item.subjectContact], ["Тип", item.requestType], ["Канал", item.channel], ["Технический расчёт", item.calculatedDueAt ? new Date(item.calculatedDueAt).toLocaleString("ru-RU") : "не применим"], ["Подтверждённый срок", new Date(item.extendedDueAt || item.confirmedDueAt).toLocaleString("ru-RU")], ["Срок подтвердил", item.dueConfirmedByName || "не зафиксировано"], ["Основание срока", item.dueConfirmationBasis || "не зафиксировано"], ["Версия", item.version]].map(([key, value]) => <div key={String(key)}><dt className="text-white/40">{key}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl><p className="mt-4 text-xs text-amber-100/80">Расчёт не учитывает официальные праздничные и перенесённые выходные дни.</p><div className="mt-4 flex gap-2"><StatusPill status={item.identityStatus === "VERIFIED" ? "ready" : "warning"} label={item.identityStatus} /><StatusPill status={Date.parse(item.extendedDueAt || item.confirmedDueAt) < Date.now() ? "critical" : "ready"} label={Date.parse(item.extendedDueAt || item.confirmedDueAt) < Date.now() ? "срок истёк" : "срок активен"} /></div></Panel>
      <Panel title="Связанные заявки"><p className="text-sm text-white/65">{item.requestIds.length ? item.requestIds.join(", ") : "Связи пока не установлены."}</p></Panel></div>
    {canChange ? <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Проверка личности"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Зафиксировать проверку" baseBody={{ action: "verifyIdentity", version: item.version }} fields={[{ name: "method", label: "Метод", kind: "select", options: ["EMAIL_CONFIRMATION", "PHONE_CONFIRMATION", "REQUEST_ID", "CONTRACT_NUMBER", "IN_PERSON_DOCUMENT", "SIGNED_ELECTRONIC_REQUEST", "OTHER_APPROVED"].map((value) => ({ value, label: value })) }, { name: "result", label: "Результат", kind: "select", options: ["ADDITIONAL_INFORMATION_REQUIRED", "VERIFIED", "FAILED", "NOT_REQUIRED"].map((value) => ({ value, label: value })) }, { name: "basis", label: "Основание и проверенные реквизиты", kind: "textarea", required: true }]} /></Panel>
      <Panel title="Продление срока"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Продлить срок" baseBody={{ action: "extend", version: item.version }} fields={[{ name: "newDueAt", label: "Новый подтверждённый срок", kind: "datetime-local", required: true, help: "Расчёт не учитывает официальные праздничные и перенесённые выходные дни." }, { name: "reason", label: "Причина и основание продления", kind: "textarea", required: true }]} /></Panel>
      <Panel title="Закрытие обращения" className="xl:col-span-2"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Зафиксировать результат" confirmText="Подтвердить завершение обращения?" baseBody={{ action: "close", version: item.version, legalBasis: item.legalBasis }} fields={[{ name: "status", label: "Итоговый статус", kind: "select", options: ["COMPLETED", "REJECTED_WITH_REASON", "CLOSED"].map((value) => ({ value, label: value })) }, { name: "responseMethod", label: "Способ ответа", required: true }, { name: "resultSummary", label: "Результат / мотивировка", kind: "textarea", required: true }]} /></Panel></div> : null}
  </InternalShell>;
}
