import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { EmptyState, Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { listLegalDocumentVersions } from "@/lib/pd-admin/registers/repository";

export const dynamic = "force-dynamic";
export default async function LegalDocumentsPage() {
  const context = await requirePdPageContext("VIEW_LEGAL_DOCUMENT_VERSIONS"); const items = listLegalDocumentVersions(context) as Array<Record<string, unknown>>; const canManage = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close();
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Версионность" title="Юридические документы" description="Старая версия не перезаписывается. Здесь регистрируются хеш и сведения об утверждении; файл должен быть помещён в закрытый архив отдельно." />{canManage ? <Panel title="Зарегистрировать новую версию" className="mb-4"><SecureMutationForm csrfToken={shell.csrfToken} endpoint="/api/internal/personal-data/legal-documents" submitLabel="Зарегистрировать версию" fields={[{ name: "documentType", label: "Тип", kind: "select", options: ["PRIVACY_POLICY", "PERSONAL_DATA_CONSENT", "MARKETING_CONSENT", "COOKIE_POLICY", "USER_AGREEMENT", "OTHER"].map((value) => ({ value, label: value })) }, { name: "version", label: "Версия", required: true }, { name: "effectiveFrom", label: "Действует с", kind: "datetime-local", required: true }, { name: "effectiveTo", label: "Действует до", kind: "datetime-local" }, { name: "contentSha256", label: "SHA-256 содержимого", required: true }, { name: "status", label: "Статус", required: true, defaultValue: "APPROVED" }, { name: "approvalBasis", label: "Основание утверждения", kind: "textarea", required: true }]} /></Panel> : null}<Panel>{items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-xs"><thead className="text-white/40"><tr>{["Тип", "Версия", "Действует с", "Действует до", "SHA-256", "Статус", "Основание"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={String(item.id)} className="border-b border-white/5"><td className="px-3 py-3">{String(item.document_type)}</td><td className="px-3 py-3">{String(item.version)}</td><td className="px-3 py-3">{new Date(String(item.effective_from)).toLocaleString("ru-RU")}</td><td className="px-3 py-3">{item.effective_to ? new Date(String(item.effective_to)).toLocaleString("ru-RU") : "—"}</td><td className="max-w-[220px] break-all px-3 py-3">{String(item.content_sha256)}</td><td className="px-3 py-3"><StatusPill status={item.status === "APPROVED" ? "ready" : "warning"} label={String(item.status)} /></td><td className="px-3 py-3">{String(item.approval_basis)}</td></tr>)}</tbody></table></div> : <EmptyState>Версии не зарегистрированы.</EmptyState>}</Panel></InternalShell>;
}
