import { StepUpForm } from "@/components/pd-admin/ActionControls";
import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { isStepUpActive } from "@/lib/pd-admin/auth/session";
import { getExport } from "@/lib/pd-admin/export/service";

export const dynamic = "force-dynamic";
export default async function ExportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const context = await requirePdPageContext("VIEW_EXPORTS"); const item = getExport(context, id); const role = context.user.role; const canChange = role === "ADMIN" || role === "PERSONAL_DATA_OFFICER" || role === "MANAGER"; const privileged = role === "ADMIN" || role === "PERSONAL_DATA_OFFICER"; const stepUp = isStepUpActive(context.session.stepUpUntil); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close(); const endpoint = `/api/internal/personal-data/exports/${encodeURIComponent(id)}`; const status = String(item.stage4_status); const version = Number(item.version);
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Официальная выгрузка" title={`Пакет ${id.slice(0, 12)}…`} description="Финальный SHA-256 ZIP хранится вне архива. Передача выполняется человеком и регистрируется отдельно." /><Panel title="Состояние"><div className="mb-4"><StatusPill status={status === "READY" ? "ready" : status === "FAILED" ? "critical" : "warning"} label={status} /></div><dl className="grid gap-3 text-sm sm:grid-cols-3">{[["Тип", item.export_type], ["Номер", item.request_number], ["Записей", item.records_count], ["Consent", item.consent_records_count], ["Вложений", item.attachments_count], ["Размер", item.total_bytes], ["Истекает", item.expires_at], ["SHA-256 ZIP", item.archive_sha256], ["SHA-256 manifest", item.manifest_sha256], ["Self approval", item.approval_self_used ? "Да" : "Нет"], ["Версия", version]].map(([k, v]) => <div key={String(k)}><dt className="text-white/40">{String(k)}</dt><dd className="mt-1 break-all">{String(v ?? "—")}</dd></div>)}</dl></Panel>
    {!stepUp && privileged ? <Panel title="Требуется step-up" className="mt-4"><StepUpForm csrfToken={shell.csrfToken} /></Panel> : null}
    <div className="mt-4 grid gap-4 xl:grid-cols-2">{status === "DRAFT" && canChange ? <Panel title="Предварительный состав"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Построить preview" baseBody={{ action: "preview", version }} fields={[]} /></Panel> : null}
      {status === "PREVIEW_READY" && privileged ? <Panel title="Утверждение минимизации"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Утвердить состав" confirmText="Подтвердить минимизацию состава? Self-approval будет явно зафиксирован." baseBody={{ action: "approve", version }} fields={[]} /></Panel> : null}
      {status === "APPROVAL_REQUIRED" && privileged ? <Panel title="Сборка архива"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Сформировать ZIP" confirmText="Сформировать защищённый временный архив?" baseBody={{ action: "build", version }} fields={[]} /></Panel> : null}
      {["READY", "DOWNLOADED", "TRANSFERRED"].includes(status) && privileged ? <Panel title="Защищённое скачивание"><a href={`/api/internal/personal-data/exports/${encodeURIComponent(id)}/download`} className="inline-block border border-[#ea5b0c] px-5 py-3 text-xs font-bold uppercase text-[#ea5b0c]">Скачать ZIP</a><p className="mt-3 text-xs text-white/45">Нужна активная step-up. Скачивание журналируется.</p></Panel> : null}
      {["READY", "DOWNLOADED"].includes(status) && privileged ? <Panel title="Зарегистрировать ручную передачу"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Зафиксировать передачу" baseBody={{ action: "transfer", legalBasis: item.legal_basis, version }} fields={[{ name: "transferredAt", label: "Дата передачи", kind: "datetime-local", required: true }, { name: "channel", label: "Канал", kind: "select", options: ["OFFICIAL_PORTAL", "SECURE_SYSTEM", "REGISTERED_MAIL", "IN_PERSON", "OTHER_APPROVED"].map((value) => ({ value, label: value })) }, { name: "recipientReference", label: "Получатель / реквизит", required: true }, { name: "registrationNumber", label: "Регистрационный номер", required: true }, { name: "transferReference", label: "Подтверждение передачи", required: true }, { name: "confirmedBy", label: "Технический ID подтверждающего" }, { name: "result", label: "Результат", kind: "textarea", required: true }]} /></Panel> : null}</div>
    {item.preview_json ? <Panel title="Preview" className="mt-4"><pre className="overflow-x-auto whitespace-pre-wrap text-xs text-white/65">{JSON.stringify(JSON.parse(String(item.preview_json)), null, 2)}</pre></Panel> : null}
  </InternalShell>;
}
