import { StepUpForm } from "@/components/pd-admin/ActionControls";
import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { isStepUpActive } from "@/lib/pd-admin/auth/session";
import { getDeletionJob } from "@/lib/pd-admin/retention/service";

export const dynamic = "force-dynamic";
export default async function DeletionPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const context = await requirePdPageContext("VIEW_RETENTION"); const item = getDeletionJob(context, id); const privileged = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const stepUp = isStepUpActive(context.session.stepUpUntil); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close(); const endpoint = `/api/internal/personal-data/deletions/${encodeURIComponent(id)}`; const status = String(item.stage4_status); const version = Number(item.version);
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Задание удаления" title={`Задание ${id.slice(0, 12)}…`} description="Уничтожаются только явно проверенные пути fixture/production-хранилища после approval. Consent-audit следует собственному сроку." /><Panel title="Состояние"><div className="mb-4"><StatusPill status={status === "COMPLETED" ? "ready" : status === "FAILED" || status === "PARTIALLY_COMPLETED" ? "critical" : "warning"} label={status} /></div><dl className="grid gap-3 text-sm sm:grid-cols-3">{[["Режим", item.stage4_mode], ["Кандидатов", item.candidates_count], ["Удалено", item.deleted_count], ["Пропущено", item.skipped_count], ["SHA-256 отчёта", item.report_sha256], ["SHA-256 акта", item.act_sha256], ["Self approval", item.approval_self_used ? "Да" : "Нет"], ["Версия", version]].map(([k, v]) => <div key={String(k)}><dt className="text-white/40">{String(k)}</dt><dd className="mt-1 break-all">{String(v ?? "—")}</dd></div>)}</dl></Panel>
    {!stepUp && privileged ? <Panel title="Опасные действия требуют step-up" className="mt-4"><StepUpForm csrfToken={shell.csrfToken} /></Panel> : null}
    {privileged ? <div className="mt-4 grid gap-4 xl:grid-cols-2">{status === "CANDIDATES" ? <Panel title="Human approval"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Утвердить подходящих кандидатов" confirmText="Подтвердить переход от DRY_RUN к контролируемому удалению?" baseBody={{ action: "approve", version }} fields={[{ name: "reason", label: "Основание утверждения", kind: "textarea", required: true }]} /></Panel> : null}{status === "HUMAN_APPROVAL" ? <Panel title="Физическое удаление"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Выполнить удаление" confirmText="Это физически удалит только утверждённые файлы. Продолжить?" baseBody={{ action: "execute", version }} fields={[]} /></Panel> : null}{status === "VERIFYING" ? <Panel title="Проверка и акт"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Проверить и создать акт" baseBody={{ action: "verify", version }} fields={[]} /></Panel> : null}</div> : null}
    <Panel title="Кандидаты и блокировки" className="mt-4"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="text-white/40"><tr>{["Request ID", "Срок", "Consent до", "Статус", "Блокировки"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{item.candidates.map((candidate) => <tr key={String(candidate.request_id)} className="border-b border-white/5"><td className="px-3 py-3">{String(candidate.request_id)}</td><td className="px-3 py-3">{new Date(String(candidate.expires_at)).toLocaleString("ru-RU")}</td><td className="px-3 py-3">{candidate.consent_expires_at ? new Date(String(candidate.consent_expires_at)).toLocaleString("ru-RU") : "—"}</td><td className="px-3 py-3">{String(candidate.status)}</td><td className="px-3 py-3">{String(candidate.blockers_json)}</td></tr>)}</tbody></table></div></Panel>
  </InternalShell>;
}
