import Link from "next/link";
import { StepUpForm } from "@/components/pd-admin/ActionControls";
import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { EmptyState, Pager, Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { isStepUpActive } from "@/lib/pd-admin/auth/session";
import { listDeletionJobs } from "@/lib/pd-admin/retention/service";

export const dynamic = "force-dynamic";
export default async function DeletionsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const context = await requirePdPageContext("VIEW_RETENTION"); const result = listDeletionJobs(context, Number((await searchParams).page || 1)); const privileged = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const stepUp = isStepUpActive(context.session.stepUpUntil); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close();
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Контролируемое уничтожение" title="Задания удаления" description="Новый процесс всегда начинается с DRY_RUN. Никаких удалений при открытии страницы или сканировании не выполняется." />{privileged ? <Panel title="Создать DRY_RUN" className="mb-4"><SecureMutationForm csrfToken={shell.csrfToken} endpoint="/api/internal/personal-data/deletions" submitLabel="Просканировать кандидатов" successHref="/internal/personal-data/deletions/{id}" baseBody={{ mode: "DRY_RUN" }} fields={[{ name: "reason", label: "Основание сканирования", kind: "textarea", required: true }]} /></Panel> : null}{!stepUp && privileged ? <Panel title="Утверждение требует step-up" className="mb-4"><StepUpForm csrfToken={shell.csrfToken} /></Panel> : null}<Panel>{result.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-white/40"><tr>{["ID", "Режим", "Статус", "Создано", "Кандидатов", "Удалено", "Пропущено", "Self approval"].map((h) => <th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{result.items.map((item) => <tr key={String(item.id)} className="border-b border-white/5"><td className="px-3 py-3"><Link prefetch={false} href={`/internal/personal-data/deletions/${item.id}`} className="text-[#ea5b0c]">{String(item.id).slice(0, 12)}…</Link></td><td className="px-3 py-3">{String(item.stage4_mode)}</td><td className="px-3 py-3"><StatusPill status={item.stage4_status === "COMPLETED" ? "ready" : item.stage4_status === "FAILED" ? "critical" : "warning"} label={String(item.stage4_status)} /></td><td className="px-3 py-3">{new Date(String(item.started_at)).toLocaleString("ru-RU")}</td><td className="px-3 py-3">{String(item.candidates_count)}</td><td className="px-3 py-3">{String(item.deleted_count)}</td><td className="px-3 py-3">{String(item.skipped_count)}</td><td className="px-3 py-3">{item.approval_self_used ? "Да" : "Нет"}</td></tr>)}</tbody></table></div> : <EmptyState>Заданий нет.</EmptyState>}<Pager basePath="/internal/personal-data/deletions" {...result} /></Panel></InternalShell>;
}
