import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { getIncident } from "@/lib/pd-admin/incidents/repository";

export const dynamic = "force-dynamic";
export default async function IncidentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const context = await requirePdPageContext("VIEW_INCIDENTS"); const item = getIncident(context, id); const canChange = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close(); const endpoint = `/api/internal/personal-data/incidents/${encodeURIComponent(id)}`;
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Инцидент" title={`Инцидент ${id.slice(0, 12)}…`} description="Связанные заявки блокируются от удаления до завершения оценки и документированного закрытия." /><Panel title="Состояние"><div className="mb-4"><StatusPill status={item.stage4_status === "CLOSED" ? "ready" : "warning"} label={String(item.stage4_status)} /></div><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Выявлен", item.detected_at], ["Описание", item.description], ["Системы", item.affected_systems], ["Категории", item.data_categories], ["Число субъектов", item.estimated_subjects], ["Оценка уведомления", item.notification_assessment_basis], ["Версия", item.version], ["Заявки", item.requestIds.join(", ")]].map(([k, v]) => <div key={String(k)}><dt className="text-white/40">{String(k)}</dt><dd className="mt-1 break-words">{String(v ?? "—")}</dd></div>)}</dl></Panel>
    {canChange && item.stage4_status !== "CLOSED" ? <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Обновить оценку"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Сохранить этап" baseBody={{ action: "update", version: item.version }} fields={[{ name: "status", label: "Статус", kind: "select", options: ["OPEN", "ASSESSMENT", "CONTAINED", "NOTIFICATION_REQUIRED", "NOTIFIED", "INVESTIGATION", "REMEDIATION"].map((value) => ({ value, label: value })) }, { name: "description", label: "Описание", kind: "textarea", required: true, defaultValue: String(item.description) }, { name: "affectedSystems", label: "Системы", kind: "textarea", required: true, defaultValue: String(item.affected_systems) }, { name: "dataCategories", label: "Категории", kind: "textarea", required: true, defaultValue: String(item.data_categories) }, { name: "estimatedSubjects", label: "Число субъектов", kind: "number", min: 0, defaultValue: Number(item.estimated_subjects || 0) }, { name: "initialMeasures", label: "Первичные меры", kind: "textarea", required: true, defaultValue: String(item.initial_measures) }, { name: "rknNotificationRequired", label: "Ответственный определил необходимость уведомления", kind: "checkbox" }, { name: "notificationAssessmentBasis", label: "Основание оценки уведомления", kind: "textarea", required: true }, { name: "legalBasis", label: "Основание изменения", kind: "textarea", required: true }, { name: "investigationResult", label: "Результат расследования", kind: "textarea" }, { name: "remediation", label: "Меры устранения", kind: "textarea" }]} /></Panel><Panel title="Закрыть инцидент"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Закрыть" confirmText="Подтвердить документированное закрытие инцидента?" baseBody={{ action: "close", version: item.version }} fields={[{ name: "legalBasis", label: "Основание", kind: "textarea", required: true }, { name: "investigationResult", label: "Результат расследования", kind: "textarea", required: true }, { name: "remediation", label: "Выполненные меры", kind: "textarea", required: true }]} /></Panel></div> : null}
  </InternalShell>;
}
