import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { getLegalHold } from "@/lib/pd-admin/legal-holds/repository";

export const dynamic = "force-dynamic";
export default async function LegalHoldPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const context = await requirePdPageContext("VIEW_LEGAL_HOLD"); const item = getLegalHold(context, id); const canChange = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; context.close(); const endpoint = `/api/internal/personal-data/legal-holds/${encodeURIComponent(id)}`;
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Legal hold" title={`Блокировка ${id.slice(0, 12)}…`} description="Снятие одной блокировки не снимает другие активные основания по связанным заявкам." /><Panel title="Состояние"><div className="mb-4"><StatusPill status={item.stage4_status === "ACTIVE" ? "warning" : item.stage4_status === "RELEASED" ? "disabled" : "critical"} label={String(item.stage4_status)} /></div><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Причина", item.reason], ["Документ", item.basis_document], ["Пересмотр", item.review_at], ["Завершён", item.ended_at], ["Версия", item.version], ["Заявки", item.requestIds.join(", ")]].map(([k, v]) => <div key={String(k)}><dt className="text-white/40">{String(k)}</dt><dd className="mt-1 break-words">{String(v ?? "—")}</dd></div>)}</dl></Panel>
    {canChange && item.stage4_status !== "RELEASED" ? <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Пересмотр"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Зафиксировать пересмотр" baseBody={{ action: "review", version: item.version }} fields={[{ name: "status", label: "Статус", kind: "select", options: ["ACTIVE", "REVIEW_REQUIRED"].map((value) => ({ value, label: value })) }, { name: "reviewAt", label: "Следующий пересмотр", kind: "datetime-local", required: true }, { name: "reason", label: "Актуализированное основание", kind: "textarea", required: true }]} /></Panel><Panel title="Снять legal hold"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Снять блокировку" confirmText="Подтвердить снятие legal hold? Система повторно проверит другие основания." baseBody={{ action: "release", version: item.version }} fields={[{ name: "reason", label: "Причина снятия", kind: "textarea", required: true }]} /></Panel></div> : null}
  </InternalShell>;
}
