import { InternalPageHeader, InternalShell } from "@/components/pd-admin/InternalShell";
import { SecureMutationForm } from "@/components/pd-admin/Stage4Forms";
import { Panel, StatusPill } from "@/components/pd-admin/Ui";
import { requirePdPageContext } from "@/lib/pd-admin/auth/page-context";
import { getAuthorityRequest } from "@/lib/pd-admin/authority-requests/repository";

export const dynamic = "force-dynamic";
export default async function AuthorityRequestPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const context = await requirePdPageContext("VIEW_AUTHORITY_REQUESTS"); const item = getAuthorityRequest(context, id); const shell = { user: context.user, session: context.session, csrfToken: context.csrfToken }; const canChange = ["ADMIN", "PERSONAL_DATA_OFFICER"].includes(context.user.role); context.close(); const endpoint = `/api/internal/personal-data/authority-requests/${encodeURIComponent(id)}`;
  return <InternalShell {...shell}><InternalPageHeader eyebrow="Запрос госоргана" title={String(item.registration_number)} description="Доступ органу к системе не предоставляется. Пакет готовится выборочно и передаётся человеком по официальному каналу." /><div className="grid gap-4 xl:grid-cols-2"><Panel title="Реквизиты"><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Орган", item.authority_name], ["Документ", item.request_number], ["Дата", item.request_date], ["Проверка", item.verification_status], ["Статус", item.status], ["Срок", new Date(String(item.extended_due_at || item.due_at)).toLocaleString("ru-RU")], ["Версия", item.version]].map(([k, v]) => <div key={String(k)}><dt className="text-white/40">{String(k)}</dt><dd className="mt-1 break-words">{String(v ?? "—")}</dd></div>)}</dl><div className="mt-4"><StatusPill status={item.verification_status === "VERIFIED" ? "ready" : "warning"} label={String(item.verification_status)} /></div></Panel><Panel title="Связанные заявки"><p className="text-sm text-white/65">{item.requestIds.length ? item.requestIds.join(", ") : "Связи не установлены."}</p></Panel></div>
    {canChange ? <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Проверка полномочий"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Зафиксировать проверку" baseBody={{ action: "verify", version: item.version }} fields={[{ name: "verificationStatus", label: "Результат", kind: "select", options: ["ADDITIONAL_INFORMATION_REQUIRED", "VERIFIED", "FAILED"].map((value) => ({ value, label: value })) }, { name: "verificationBasis", label: "Проверенные реквизиты и основание", kind: "textarea", required: true }]} /></Panel><Panel title="Продление срока"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Продлить" baseBody={{ action: "extend", version: item.version }} fields={[{ name: "newDueAt", label: "Новый срок", kind: "datetime-local", required: true }, { name: "reason", label: "Причина", kind: "textarea", required: true }]} /></Panel><Panel title="Закрытие" className="xl:col-span-2"><SecureMutationForm csrfToken={shell.csrfToken} endpoint={endpoint} method="PATCH" submitLabel="Зафиксировать результат" confirmText="Подтвердить завершение запроса?" baseBody={{ action: "close", version: item.version, legalBasis: item.legal_basis }} fields={[{ name: "status", label: "Итог", kind: "select", options: ["COMPLETED", "REJECTED_WITH_REASON", "CLOSED"].map((value) => ({ value, label: value })) }, { name: "responseChannel", label: "Канал ответа", required: true }, { name: "responseSentAt", label: "Дата ответа", kind: "datetime-local", required: true }, { name: "resultSummary", label: "Результат", kind: "textarea", required: true }]} /></Panel></div> : null}
  </InternalShell>;
}
